### ISSUE TITLE
Epic 1: Implement User Authentication and Login

### ISSUE THREAD

**Issue by ruchitha007** [BitBytes-team/project7#1]
As a developer, I want the assignee to develop a comprehensive user authentication system to log in to my account, access personalized features, and ensure my data is secure. 

Acceptance Criteria: 

1.User Authentication and Greeting: 

•When launching the app and not logged in, the toolbar should display "Please Login." 

•Attempting to navigate to any view without being logged in (e.g., via deep links) should automatically redirect to the LoginRegister view. 

•In the LoginRegister view, users should enter their login name and successfully log in. 

•After successful login, the toolbar should display "Hi <firstname>" where <firstname> is the user's first name. 

•The toolbar should include a "Logout" button for user log out. 

•If the login attempt fails (e.g., due to an invalid login name), the app should display an appropriate error message, allowing the user to retry. 

.Backend Enhancements for User Login: 

•Extend the Mongoose schema for the User model with a new property named login_name, which is a string for the user's login name. 

•Introduce two new REST API calls: 

•/admin/login: This endpoint should allow the LoginRegister view to log in a user by sending a POST request with a JSON-encoded body containing the login_name. If the login fails, the server should respond with an HTTP status of 400 (Bad Request). If the login is successful, the server should store the necessary information in the Express session. 

•/admin/logout: Sending a POST request with an empty body to this URL should log the user out by clearing the session data. If the user is not currently logged in, the server should return an HTTP status of 400 (Bad Request). 

3.Handling Unauthorized Requests: 

•Update the web server to handle unauthorized requests correctly. 

•All requests, except for /admin/login and /admin/logout, should be configured to reject the request with an HTTP status of 401 (Unauthorized) if the session data does not indicate that a user is currently logged in. This ensures that unauthorized access to protected resources is prevented effectively.

**Comment by Sharu201101** [comment]
This is the progress for the problem 1. Till now login and logout functionalities have been added and are working successfully. Handling of uploading photos has to be worked on. 

import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter, Route, Switch, Redirect } from 'react-router-dom';
import { Grid, Paper, Typography } from '@mui/material';
import './styles/main.css';

import LoginRegister from './components/loginRegister/LoginRegister';
import TopBar from './components/topBar/TopBar';
import UserDetail from './components/userDetail/userDetail';
import UserList from './components/userList/userList';
import UserPhotos from './components/userPhotos/userPhotos';

class PhotoShare extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      appContext: "",
      checked: false,
      upload: false,
      version: "",
      userIsLoggedIn: Boolean(localStorage.getItem("sessionState")),
      user: null,
    };
  }

  componentDidMount() {
    let userId = localStorage.getItem("sessionState");
    if (userId) {
      let formData = {
        user_id: userId,
      };
      axios.post("/admin/login", formData).then(response => {
        // console.log(response.data);
        this.setState({
          userIsLoggedIn: true,
          user: response.data,
        });
      }).catch(error => {
        localStorage.removeItem("sessionState");
        this.setState({
          userIsLoggedIn: false,
          user: null,
        });
        console.log(error.response.data);
      });
    }
    axios.get("/test/info").then(response => {
      this.setState({
        version: Version: ${response.data.version},
      });
    }).catch(error => {
      console.log(error.message);
    });
  }

  componentDidUpdate() {
    this.getRoot();
  }

  setContext = (newContext) => {
    this.setState({
      appContext: newContext,
    });
  }

  handleChange = () => {
    this.setState(prevState => ({
      checked: !prevState.checked,
    }));
  };

  handlinglogin = (data) => {
    localStorage.setItem("sessionState", data._id);
    this.setState({
      userIsLoggedIn: true,
      user: data,
    });
  };

  handlinglogout = () => {
    axios.post("/admin/logout", {}).then(response => {
      console.log(response.data);
      localStorage.removeItem("sessionState");
      this.setState({
        userIsLoggedIn: false,
        user: null,
      });
    }).catch(error => {
      console.log(error.message);
    });
  };

  getRoot = () => {
    return this.state.userIsLoggedIn ? <Redirect to="/" /> : <Redirect to="/login-register" />
  };

  getLogin = () => {
    return this.state.userIsLoggedIn ? <Redirect to={/users/${this.state.user._id}} /> :
        <LoginRegister setContext={this.setContext}
                       handlinglogin={this.handlinglogin} />
  };

  render() {
    return (
        <BrowserRouter>
          <div>
            <Grid container spacing={8}>
              <Grid item xs={12}>
                <TopBar topName={this.state.topname}
                        appContext={this.state.appContext}
                        user={this.state.user}
                        version={this.state.version}
                        checked={this.state.checked}
                        userIsLoggedIn={this.state.userIsLoggedIn}
                        handleChange={this.handleChange}
                        handlinglogout={this.handlinglogout}
                />
              </Grid>
              <div className="main-topbar-buffer" />
              <Grid item sm={2}>
                <Paper className="main-grid-item">
                  <UserList setTopName={this.setTopName}
                            setContext={this.setContext} checked={this.state.checked}
                            userIsLoggedIn={this.state.userIsLoggedIn}
                  />
                </Paper>
              </Grid>
              <Grid item sm={10}>
                <Paper className="main-grid-item">
                <Switch>
                  <Route path="/login-register"
                         render={this.getLogin}
                  />
                  {
                    this.state.userIsLoggedIn ?
                        <Route path="/users/:userId"
                               render={props => <UserDetail {...props} setContext={this.setContext}

                               />}
                        />
                        :
                        <Redirect path="/users/:id" to="/login-register" />
                  }
                  {
                    this.state.userIsLoggedIn ?
                        <Route path="/photos/:userId"
                               render={props => <UserPhotos {...props}
                                                            setContext={this.setContext}
                                                            checked={this.state.checked}
                                                            upload={this.state.upload}
                               />}
                        />
                        :
                        <Redirect path="/users/:id" to="/login-register" />
                  }
                  {
                    this.state.userIsLoggedIn ?
                        <Route path="/comments/:userId"
                               render={props => <UserComments {...props} setContext={this.setContext}
                                                              checked={this.state.checked}/>}
                        />
                        :
                        <Redirect path="/users/:id" to="/login-register" />
                  }
                  {
                    this.state.userIsLoggedIn ?
                        <Route path="/favorites"
                               render={props => <FavoriteList {...props} setContext={this.setContext}
                                                              user={this.state.user} />}
                        />
                        :
                        <Redirect path="/users/:id" to="/login-register" />
                  }
                  {
                    this.state.userIsLoggedIn ?
                        <Route path="/users" component={UserList} />
                        :
                        <Redirect path="/users/:id" to="/login-register" />
                  }
                  <Route render={this.getRoot} />
                </Switch>
                </Paper>
              </Grid>
            </Grid>
          </div>
        </BrowserRouter>
    );
  }
}

ReactDOM.render(<PhotoShare />, document.getElementById('photoshareapp'));

**Comment by Sharu201101** [comment]
import React from 'react';
import ReactDOM from 'react-dom';
import { HashRouter, Route, Switch, Redirect } from 'react-router-dom';
import { Grid, Typography, Paper } from '@material-ui/core';
import './styles/main.css';

// import necessary components
import TopBar from './components/topBar/TopBar';
import UserDetail from './components/userDetail/userDetail';
import UserList from './components/userList/userList';
import UserPhotos from './components/userPhotos/userPhotos';
import LoginRegister from './components/loginRegister/loginRegister';

class PhotoShare extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      userName: null,            // which user the login user is viewing
      loginUser: null,           // use to check if an user is logged
      photoIsUploaded: false
      /**
       * * login user's first name and id
       * * fetched from loginRegister component and pass up to the whole App
       * * for other child componenets use
       *  */ 
    };
  }

  /**
   * To get user name from child component and return back for TopBar to display
   * @param userName user last name and first name
   */
  handleUserNameChange = userName => this.setState({ userName: userName });

  /**
   * To get login user name from child component and return back for TopBar to display
   * @param loginUser user's id and first name
   */
  handleLoginUserChange = loginUser => this.setState({ loginUser: loginUser });

  /**
   * To let child component be notified photos list is updated
   */
  handlePhotoUpload = () => {
    this.setState({ photoIsUploaded: true });  // notify photos list re-render
    this.setState({ photoIsUploaded: false }); // reset the photoIsUploaded variable
  };

  render() {
    const paths = ["/users/:userId", "/photos/:userId", ""]; // paths to render in the Topbar

    return (
      <HashRouter>
        <div>
          <Grid container spacing={1}>
            {/* TopBar View */}
            <Grid item xs={12}>
              <Switch>
                {/* Use paths.map() to populate the same Topbar component for different routes */}
                {paths.map((path) => (
                  <Route key={path} path={path}>
                    {(props) => (
                      <TopBar
                        {...props}
                        onLoginUserChange={this.handleLoginUserChange}
                        onPhotoUpload={this.handlePhotoUpload}
                        userName={this.state.userName}
                        loginUser={this.state.loginUser}
                      />
                    )}
                  </Route>
                ))}
              </Switch>
            </Grid>

            <div className="cs142-main-topbar-buffer" />

            {/* Sidebar View */}
            <Grid item sm={3}>
              <Paper className="side-bar" elevation={3}>
                <UserList loginUser={this.state.loginUser} />
              </Paper>
            </Grid>

            {/* Main View */}
            <Grid item sm={9}>
              <Paper className="cs142-main-grid-item" elevation={3}>
                {/* ALl unauthorized visit would go to login page */}
                <Switch>
                  {/* Login/Register View */}
                  <Route path="/login-register">
                    <LoginRegister
                      onLoginUserChange={this.handleLoginUserChange}
                      loginUser={this.state.loginUser}
                    />
                  </Route>
                  {/* User detail View */}
                  <Route path="/users/:userId">
                    {(props) => (
                      <UserDetail
                        {...props}
                        onUserNameChange={this.handleUserNameChange}
                        loginUser={this.state.loginUser}
                      />
                    )}
                    {/* Pass "props": to use "this.props.match.params" */}
                  </Route>
                  {/* User photo View */}
                  <Route path="/photos/:userId">
                    {(props) => (
                      <UserPhotos
                        {...props}
                        onUserNameChange={this.handleUserNameChange}
                        photoIsUploaded={this.state.photoIsUploaded}
                        loginUser={this.state.loginUser}
                      />
                    )}
                  </Route>
                  {/* User list View */}
                  <Route path="/users">
                    {this.state.loginUser ? (
                      <UserList loginUser={this.state.loginUser} />
                    ) : (
                      <Redirect to={`/login-register`} />
                    )}
                  </Route>
                  {/* Home page View */}
                  <Route path="/">
                    {this.props.loginUser ? (
                      <Typography variant="h3">
                        Welcome to my photosharing app!
                      </Typography>
                    ) : (
                      <Redirect to={`/login-register`} />
                    )}
                  </Route>
                </Switch>
              </Paper>
            </Grid>
          </Grid>
        </div>
      </HashRouter>
    ); // end of return
  } // end of render
} 

// Create React App
ReactDOM.render(<PhotoShare/>, 
document.getElementById('photoshareapp'));
