### ISSUE TITLE
Epic 4 : User Registration and Password Enhancement

### ISSUE THREAD

**Issue by Sharu201101** [BitBytes-team/project7#10]
As a developer, I want the assignee to be able to register an account and enhance the security of my account with a password, so that I can access the application securely and enjoy personalized features. 

Acceptance Criteria: 

- As a new user, I can see a "Register Me" button in the LoginRegister view, which allows me to create a new account. 
- The registration form should include fields for login_name, password, first_name, last_name, location, description, and occupation. 
- The registration form should include two password fields to confirm that the user has entered the same password correctly. 
Upon registration, the system should validate the following conditions: 

1. The login_name should be unique and not already in use. 
2. The first_name, last_name, and password fields must be non-empty strings. 
3. If the registration is successful, the system should create a new user account in the database with the provided information. 

- If registration fails due to validation errors (e.g., non-unique login_name, empty fields), a clear error message should be displayed, specifying the reason for failure. 
- Upon successful registration, a success message should be displayed, and the registration form input fields should be cleared, making it convenient for the user to log in. 
- The system should ensure that passwords typed by the user are not visible in the view for security reasons. 
- Passwords should be securely stored, and best practices for password hashing and security should be followed for data protection. 
- The web server should support a POST request to the /user endpoint for user registration, taking a JSON-encoded body with the specified properties: login_name, password, first_name, last_name, location, description, and occupation. 
- The server should validate the input data for registration, and if any errors occur, it should return an HTTP status of 400 along with a clear error message. 
- The LoginRegister view should support logging in with a password, and the password should be checked as part of the POST request to /admin/login. 
- The user registration and password enhancement should adhere to security best practices to protect user data and privacy.

**Comment by suhasss077** [comment]
Kindly review the above the acceptance criteria and develop the code for the same

**Comment by Sharu201101** [comment]
Considering the above criteria, iam in midway in developing the code. I'll let you know when the code is running successfully.

**Comment by Sharu201101** [comment]
import React from 'react';
import {
    Button,
    Box,
    TextField,
    Alert,
    IconButton,
    Collapse,
    Divider,
    Accordion,
    AccordionSummary,
    AccordionDetails,
    Typography
} from '@mui/material';
import CloseIcon from '@mui/icons-material/Close';
import './loginRegister.css';
import axios from 'axios';
import {Stack} from "@mui/system";
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';

/**
 * Define TopBar, a React component of project #5
 */
class LoginRegister extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            user: {
                first_name: undefined,
                last_name: undefined,
                location: undefined,
                description: undefined,
                occupation: undefined,
                login_name: undefined,
                password: undefined,
                password_repeat: undefined,
            },
            showLoginError: false,
            showRegistrationError: false,
            showRegistrationSuccess: false,
            showRegistration: false
        };
        this.handleLogin = this.handleLogin.bind(this);
        this.handleRegister = this.handleRegister.bind(this);
        this.handleChange = this.handleChange.bind(this);
        this.handleShowRegistration = this.handleShowRegistration.bind(this);
    }

    handleShowRegistration = () => {
        const showRegistration = this.state.showRegistration;
        this.setState({
            showRegistration: !showRegistration
        });
    }
    handleLogin = () => {
        const currentState = JSON.stringify(this.state.user);
        axios.post(
            "/admin/login",
            currentState,
            {
                headers: {
                    'Content-Type': 'application/json',
                }
            })
            .then((response) =>
            {
                const user = response.data;
                this.setState({
                    showLoginError: false,
                    showRegistrationSuccess: false,
                    showRegistrationError: false,
                });
                this.props.changeUser(user);
            })
            .catch( error => {
                this.setState({
                    showLoginError: true,
                    showRegistrationSuccess: false,
                    showRegistrationError: false,
                });
                console.log(error);
            });
    }

    handleRegister = () => {
        if (this.state.password !== this.state.password_repeat){
            alert("Passwords don't match");
            return;
        }
        const currentState = JSON.stringify(this.state.user);
        axios.post(
            "/user/",
            currentState,
            {
                headers: {
                    'Content-Type': 'application/json',
                }
            })
            .then((response) =>
            {
                const user = response.data;
                this.setState({
                    showRegistrationSuccess: true,
                    showRegistrationError: false,
                    showLoginError: false,
                    showRegistration: false
                });
                this.props.changeUser(user);
            })
            .catch( error => {
                this.setState({
                    showRegistrationError: true,
                    showLoginError: false,
                    showRegistrationSuccess: false,
                });
                console.log(error);
            });
    }

    handleChange(event){
        this.setState((state) => state.user[event.target.id] = event.target.value);
    }
    componentDidMount() {
        //this.handleAppInfoChange();
    }
    render() {
        return this.state.user ? (
            <div>
                <Box component="form" autoComplete="off">
                    {this.state.showLoginError && <Alert severity="error">Login Failed</Alert>}
                    {this.state.showRegistrationError && <Alert severity="error">Registration Failed</Alert>}
                    {this.state.showRegistrationSuccess && <Alert severity="success">Registration Succeeded</Alert>}
                    <div>
                        <TextField id="login_name" label="Login Name" variant="outlined"  fullWidth
                                   margin="normal" required={true} onChange={this.handleChange}/>
                    </div>
                    <div>
                        <TextField id="password" label="Password" variant="outlined"  fullWidth
                                   margin="normal" type="password" required={true} onChange={this.handleChange}/>
                    </div>
                    <Box mb={2}>
                        <Button type="submit" variant="contained" onClick={this.handleLogin}>
                            Login
                        </Button>
                    </Box>
                    <Accordion expanded={this.state.showRegistration} onChange={this.handleShowRegistration}>
                        <AccordionSummary
                            expandIcon={<ExpandMoreIcon />}
                            aria-controls="panel1a-content"
                            id="panel1a-header"
                        >
                            <Typography>User Registration</Typography>
                        </AccordionSummary>
                        <AccordionDetails>
                            <Box>
                                <div>
                                    <TextField id="password_repeat" label="Repeat Password" variant="outlined"  fullWidth
                                               margin="normal" type="password" required={this.state.showRegistration} onChange={this.handleChange}/>
                                </div>
                                <div>
                                    <TextField id="first_name" label="First Name" variant="outlined"  fullWidth
                                               margin="normal" autoComplete="off" required={this.state.showRegistration} onChange={this.handleChange}/>
                                </div>
                                <div>
                                    <TextField id="last_name" label="Last Name" variant="outlined"  fullWidth
                                               margin="normal" required={this.state.showRegistration} onChange={this.handleChange}/>
                                </div>
                                <div>
                                    <TextField id="location" label="Location" variant="outlined"  fullWidth
                                               margin="normal" onChange={this.handleChange}/>
                                </div>
                                <div>
                                    <TextField id="description" label="Description" variant="outlined" multiline rows={4}
                                               fullWidth margin="normal" onChange={this.handleChange}/>
                                </div>
                                <div>
                                    <TextField id="occupation" label="Occupation" variant="outlined" fullWidth
                                               margin="normal" onChange={this.handleChange}/>
                                </div>
                                <div>
                                    <Button variant="contained" onClick={this.handleRegister}>
                                        Register Me
                                    </Button>
                                </div>
                            </Box>
                        </AccordionDetails>
                    </Accordion>
                </Box>
            </div>
        ) : (
            <div/>
        );
    }
}

export default LoginRegister;
