### ISSUE TITLE
Epic 1: Code Testing - Enhanced User Authentication and Login

### ISSUE THREAD

**Issue by ruchitha007** [BitBytes-team/project7#3]
As a developer, I want the assignee to thoroughly test the enhanced user authentication and login functionalities to ensure the security, functionality, and reliability of the system. This is important to deliver a secure and user-friendly application. 

Test Criteria: 
- Verify that user login with valid credentials (login_name) is successful, and the user is redirected to their profile page. 
- Verify that user login with invalid credentials (non-existing login_name) results in an appropriate error message, and the user is allowed to retry. 
- Ensure that the "Logout" button logs the user out and clears their session information. 
- Test that attempts to access restricted endpoints without being logged in are correctly rejected with a status code of 401 (Unauthorized). 
- Validate that the user's first name is displayed in the toolbar as "Hi <firstname>" when logged in. 
- Confirm that the toolbar displays "Please Login" when no user is logged in. 
- Check that the main view of the application shows the LoginRegister component when no user is logged in. 
- Ensure that deep links or attempts to navigate to different views result in redirection to the LoginRegister view when no user is logged in. 
- Verify that the left user list is populated only when a user is logged in. 
- Thoroughly test the enhanced Mongoose schema for the User model to ensure that the login_name property is correctly added and utilized. 
- Test the /admin/login API endpoint by sending valid and invalid login_name credentials via a POST request. Ensure that a valid login redirects to the user's profile, while an invalid login results in a 400 (Bad request) status and an appropriate error message. 
- Test the /admin/logout API endpoint by sending a POST request with an empty body. Verify that a logged-in user is successfully logged out, and an unauthorized user receives a 400 (Bad request) status.

**Comment by suhasss077** [comment]
All test criteria have been met, and the code has been thoroughly tested for both positive and negative scenarios.  

All test cases have passed, and any identified issues or inconsistencies have been addressed and resolved.  

The code is ready for deployment to ensure a secure and reliable user authentication system.
