### ISSUE TITLE
Problem 2:Adding Comments to Photos

### ISSUE THREAD

**Issue by ruchitha007** [BitBytes-team/project7#4]
As a developer who appreciates engaging with content, I want the assignee to have the ability to add comments to photos. This feature will enable me to express my thoughts and opinions on photos in a simple and intuitive manner, enhancing the interactive experience. 

Acceptance Criteria: 

- In the photo detail view, a user-friendly interface should be provided to add comments to photos. The interface design can be a popup dialog, input field, or any other intuitive form, making it easy to use. 
- The interface for adding comments should be clear in indicating which photo the comment is intended for, ensuring that users can easily identify the photo they are commenting on. 
- After adding a comment, the display of the photo and its comments should be updated immediately to reflect the newly added comment, providing real-time feedback. 
- The web server API should be expanded to support a new HTTP POST API: /commentsOfPhoto/:photo_id, enabling users to add comments to a specific photo identified by its unique id. 
- The POST request to /commentsOfPhoto/:photo_id should include a JSON-encoded body with a single property named "comment," which contains the text of the comment. 
- Each comment added should include the identifier of the logged-in user, ensuring that the system can associate comments with the correct users.

**Comment by BhavagnaT** [comment]
import React from "react";
import { Button, Dialog, DialogContent, DialogContentText, TextField, DialogActions, Chip } from "@material-ui/core";
import "./commentDialog.css";
import axios from "axios";

/*
 * This component is for creating a comment dialog UI, 
 * send newly added comment to server,
 * notifiy upper level for the comment added,
 * so that UserPohtos component will re-fetch data, and update UI.
 * @param this.props.handleSumbitChange: handle update notification.
 * @param this.props.photo_id: photo id that is being commmented.
 */
export default class CommentDialog extends React.Component {
    constructor(props) {
      super(props);
      this.state = { 
        open: false,
        comment: "",
      };
    }

    handleClickOpen = () => this.setState({ open: true });  // open comment dialog
    handleClickClose = () => this.setState({ open: false });// close comment dialog
    handleCommentChange = e => this.setState({ comment: e.target.value }); // reflect comment whenever user chang it

    // Handle changes after Comment submitted
    handleCommentSubmit = () => {
      const commentText = this.state.comment; // store the comment text
      this.setState({ comment: "" }); // clear output before UI disppears
      this.setState({ open: false }); // close the comment dialog UI panel

      // Send to POST request with comment text in JSON format
      axios
        .post(`/commentsOfPhoto/${this.props.photo_id}`, { comment: commentText }) // send new comment to server
        .then(() => this.props.onCommentSumbit())                 // notify upper level component to re-render UI
        .catch(error => console.log("Comment Sent Failure: ", error));
    };
  
    render() {
      return (
        <div className="comment-dialog">
          <Chip label="Reply" onClick={this.handleClickOpen}/>
          {/* onClose: when mouse click outside of the dialog box, then close the dialog */}
          <Dialog open={this.state.open} onClose={this.handleClickClose} >
            <DialogContent>
              <DialogContentText>Add a comment...</DialogContentText>
              <TextField value={this.state.comment} onChange={this.handleCommentChange} autoFocus multiline margin="dense" fullWidth />
            </DialogContent>
            <DialogActions>
              <Button onClick={this.handleClickClose}>Cancel</Button>
              <Button onClick={this.handleCommentSubmit}>Submit</Button>
            </DialogActions>
          </Dialog>
        </div>
      );
    }
  }
  
There is still some work to be done.
