### ISSUE TITLE
Epic 3 : Photo Uploading Feature

### ISSUE THREAD

**Issue by Sharu201101** [BitBytes-team/project7#7]
As a developer, I want the assignee to be able to upload new photos to share with the community, so that I can contribute to the app's content and engage with other users. 

Acceptance Criteria: 

- When I am logged in, I should see a "Add Photo" button in the main toolbar of the app. 
- Clicking on the "Add Photo" button should open a file selection dialog, allowing me to choose a photo from my local device for upload. 
- The system should validate that I have selected a file for upload. If no file is selected, I should receive a user-friendly error message, and the upload should not proceed. 
- Upon selecting and confirming the photo for upload, the app should initiate a POST request to the /photos/new endpoint of the web server. 
- The web server should handle the file upload and save the photo in the "images" directory under a unique name generated by the server. It should also create a new Photo object associated with the logged-in user, capturing the following details: 

1. The unique name of the uploaded file.
2. The creation date of the photo. 
3. The user ID of the logged-in user.

**Comment by ruchitha007** [comment]
I wanted to provide a quick update on the progress of the Photo Uploading Feature. Our development is currently underway, and here's where we stand:
Next steps include finalizing the POST request implementation and completing the server-side logic. We're committed to delivering a robust and user-friendly photo uploading feature.

import React from "react";
import { Link, Redirect } from "react-router-dom";
import { List, Divider, Typography, Grid, Avatar, Card, CardHeader, CardMedia, CardContent } from "@material-ui/core";
import "./userPhotos.css";
import axios from "axios";
import CommentDialog from "../commentDialog/commentDialog";

export default class UserPhotos extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      photos: null, // photos list where each photo contains comments list
      user: null,   // Author who posts the photo
    };
  }

  /**
   * user axios to get photos data and photo's Author data
   * from user ID
   *  */
  axios_fetch_photos_and_user() {
    // To get photo data
    axios 
    .get(`/photosOfUser/${this.props.match.params.userId}`) // photo url
    .then(response => this.setState({ photos: response.data }))
    .catch(error => console.log( "/photosOfUser/ Error: ", error));

    // To get photo's Author data
    axios
      .get(`/user/${this.props.match.params.userId}`)  // user url
      .then(response => { 
        this.setState({ user: response.data });
        this.props.onUserNameChange(response.data.first_name + ' ' + response.data.last_name);
        console.log("** UserPhotos: fetched User Photos **");
      })
      .catch(error => console.log( "/user/ Error: ", error));
  }


  /**
   * To re-fetch data from server once comment is submitted,
   * this will lead to update UI immediately once comment sent.
   */
  handleCommentSumbit = () => {
    console.log("Submit was pressed, re-rendering photos and comments");
    this.axios_fetch_photos_and_user();
  };

  /**
   * To fetch photos and author data when click the "See Photo" button.
   *  */ 
  componentDidMount() {
    // when there is an id after "/photos/<user_id>"
    if (this.props.match.params.userId) { 
      this.axios_fetch_photos_and_user();
    }
  }

  /**
   * To detect if a new photo is added, re-render if it was.
   * @param this.props.photoIsUploaded: if a new photo was updated
   */
  componentDidUpdate(prevProps) {
    if (prevProps.photoIsUploaded!==this.props.photoIsUploaded && this.props.photoIsUploaded) {
        console.log("Trigger re-render");
        this.axios_fetch_photos_and_user();
      }
  }

    
  render() {
    // If not yet login, redirect to login page
    if (!this.props.loginUser) {
      return <Redirect to={`/login-register`} />;
    }

    // If there is no user, then render below:
    if (!this.state.user) {
      return <p>Loading</p>;
    }

    // If there is user photo, then display user photos
    return (
      this.state.photos && (
        <Grid justifyContent="flex-start" container spacing={3}>
          {/* Loop through all the photos */}
          {this.state.photos.map((photo) => (

            // Each photo's layout
            <Grid item xs={6} key={photo._id}>
              <Card variant="outlined">
                {/* Each photo's author name and author post time */}
                <CardHeader
                  avatar={(
                    <Avatar style={{ backgroundColor: "#FF7F50" }}>
                      {this.state.user.first_name[0]}
                    </Avatar>
                  )}                
                  title={(
                    <Link to={`/users/${this.state.user._id}`}>
                      {`${this.state.user.first_name} ${this.state.user.last_name}`}
                    </Link>
                  )}
                  subheader={photo.date_time}
                />

                {/* Each photo's image */}
                <CardMedia
                  component="img"
                  image={`./images/${photo.file_name}`}
                  alt="Anthor Post"
                />

                {/* Comments' layout */}
                <CardContent>
                  {/* Loop through all comments under the photo */}
                  {photo.comments && (
                    <Typography variant="subtitle1">
                      Comments:
                      <Divider />
                    </Typography>
                  )}
                  {photo.comments.map((c) => (
                    <List key={c._id}>
                      <Typography variant="subtitle2">
                        <Link to={`/users/${c.user._id}`}>
                          {`${c.user.first_name} ${c.user.last_name}`}
                        </Link>
                      </Typography>
                      <Typography
                        variant="caption"
                        color="textSecondary"
                        gutterBottom
                      >
                        {c.date_time}
                      </Typography>
                      <Typography variant="body1">
                        {`"${c.comment}"`}
                      </Typography>
                    </List>
                  ))}

                  {/* Comment dialog box */}
                  <CommentDialog
                    onCommentSumbit={this.handleCommentSumbit}
                    photo_id={photo._id}
                  />
                </CardContent>

              </Card>
            </Grid>
          ))}
        </Grid>
      )
    );
  }

}
